### ISSUE TITLE
base32

### ISSUE THREAD

**Issue by deian** [PLSysSec/cargo-scan#48]
I scanned base32. Got promoted a few times, with things along the lines of:

![image](https://github.com/PLSysSec/cargo-scan/assets/374012/ef03844b-6b0d-4382-9666-3110098ab561)

For safe-to-run, it's probably worth checking `#[cfg(test)]` code but might be okay to not too; not clear?

**Comment by cdstanford** [comment]
if we want to skip `#[cfg(test)]`, that's easy to add, we are already skipping a couple of other `cfg` attributes.

I think it would make sense to skip initially, particularly for experiments related to characterizing the set of effects common in the Rust supply chain ecosystem (as opposed to downloading and running a crate yourself which is where you might care about tests)
