### ISSUE TITLE
more context?

### ISSUE THREAD

**Issue by deian** [PLSysSec/cargo-scan#49]
![image](https://github.com/PLSysSec/cargo-scan/assets/374012/030660a7-14a1-47f3-aa39-8c34edfbd12a)

I'd want to see how buff is used, but the default lines make it kind of hard; probably worth making this configurable

**Comment by deian** [comment]
if you haven't looked at rand-0.8.5, I think it's a pretty great candidate

**Comment by cdstanford** [comment]
@DavidThien says it would be not hard to add another option to the user to show more context (e.g., show 10 more lines), this could be a good short term solution.
In favor?

There is also a CLI option to change the number of lines displayed: `--lines-before` and `--lines-after`

Worth keeping in mind, this may not be the best long term solution, eventual plan is to have something more like #12 and make it easier to navigate the actual code while doing an audit. But probably worth adding for now for v0?

**Comment by DavidThien** [comment]
There's now an extra option during auditing to expand the context we show to the user. I also cleaned up the code while I was there, so we don't display the option to go the effect origin in situations it doesn't make sense.

**Comment by deian** [comment]
awesome! ill give it another shot this week!
